COOKIE_DOMAIN: "localhost"
MYSQL_CONFIG:
  type: "mysql"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  database: "database"
  synchronize: true

WEAPP_CONFIG:
  APPID: 小程序APPID
  APPSECRET: 小程序APPSECRET
  WEAPP_TOKEN_CACHE_KEY: 小程序redis key
  WEAPP_TOKEN_CACHE_TTL: 7200 - 600

REDIS_CONFIG:
  host: "127.0.0.1"  # redis 链接
  port: 6379         # redis 端口
  auth: "password"       # redis 连接密码
  db: 0              # redis 数据库